#!/usr/bin/env python3
"""W3.3 floor calibration: base-model Vietnamese output diversity baseline.

Measures distinct-2 (the plan's ONE diversity target, floor 0.45 on a
held-out 200-prompt sample) on the STUDENT BASE MODEL (Qwen3-1.7B) so the
corpus metric from w33 can be compared against the model it was calibrated
from. The plan states the floor is "the lower quartile of base-model
Vietnamese output diversity" — this script makes that number measurable.

Method: 200 Vietnamese tarot readings generated by the base model on the
corpus's own question/card prompts (same input distribution, minimal prompt,
no anti-collapse stack, temperature 0.8). distinct-2 computed with the same
tokenizer/metric as the corpus (simple_vi_tokens, unique bigram ratio).

Usage:
  python scripts/base_diversity_baseline.py [--n 200] [--seed 42]
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from tfvn.serialise import dumps_canonical, read_jsonl  # noqa: E402
from tfvn.w3_anticollapse import distinct_n  # noqa: E402

DATA_DIR = ROOT / "datasets"
RAW_DIR = DATA_DIR / "raw"


def _student_model_path() -> Path:
    hub = Path.home() / ".cache" / "huggingface" / "hub" / "models--Qwen--Qwen3-1.7B" / "snapshots"
    snaps = sorted(hub.glob("*")) if hub.exists() else []
    if not snaps:
        raise SystemExit("Qwen3-1.7B not found in HF cache")
    return snaps[-1]


def _prompt(row: Dict[str, Any]) -> str:
    cards = ", ".join(
        f'{c["name_en"]} ({"ngược" if c["orientation"] == "reversed" else "xuôi"})'
        for c in row["cards_used"]
    )
    return f"Câu hỏi: {row['question_vi']}\nCác lá bài: {cards}\nHãy luận giải."


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n", type=int, default=200)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--model", type=str, default="", help="model path (default: HF cache Qwen3-1.7B)")
    ap.add_argument("--max-tokens", type=int, default=320)
    ap.add_argument("--batch", type=int, default=4)
    args = ap.parse_args()

    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    rows = read_jsonl(RAW_DIR / "generated.jsonl")
    main = [
        r for r in rows
        if not any(p in (r.get("provenance") or [])
                   for p in ("safety_slice", "grounding_negative", "counter_sycophancy"))
    ]
    if len(main) < args.n:
        print(f"need {args.n} prompts, have {len(main)}", file=sys.stderr)
        return 1
    prompts = [_prompt(r) for r in main[: args.n]]

    model_path = Path(args.model) if args.model else _student_model_path()
    print(f"model: {model_path.name}")
    tok = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForCausalLM.from_pretrained(
        model_path, torch_dtype=torch.float16, device_map="auto"
    )
    model.eval()
    if tok.pad_token_id is None:
        tok.pad_token_id = tok.eos_token_id
    tok.padding_side = "left"

    torch.manual_seed(args.seed)
    outputs: List[str] = []
    t0 = time.time()
    with torch.no_grad():
        for i in range(0, len(prompts), args.batch):
            enc = tok(prompts[i:i + args.batch], return_tensors="pt", padding=True)
            enc = {k: v.to(model.device) for k, v in enc.items()}
            out = model.generate(
                **enc,
                max_new_tokens=args.max_tokens,
                do_sample=True,
                temperature=0.8,
                top_p=0.95,
                pad_token_id=tok.pad_token_id,
            )
            for j, ids in enumerate(out):
                gen = ids[len(enc["input_ids"][j]):]
                outputs.append(tok.decode(gen, skip_special_tokens=True).strip())
            done = min(i + args.batch, len(prompts))
            if done % 40 == 0 or done == len(prompts):
                print(f"  {done}/{len(prompts)} generated ({time.time() - t0:.0f}s elapsed)")
    del model
    torch.cuda.empty_cache()

    sample200 = outputs[:200] if len(outputs) >= 200 else outputs
    windows = [distinct_n(outputs[i:i + 100]) for i in range(0, len(outputs), 100)]
    report = {
        "schema": "base_diversity_baseline",
        "model": "Qwen/Qwen3-1.7B",
        "n": len(outputs),
        "temperature": 0.8,
        "max_tokens": args.max_tokens,
        "prompt_source": "corpus main-loop question/card prompts (minimal prompt, no stack)",
        "distinct2_200_sample": distinct_n(sample200),
        "distinct2_per_100_windows": [round(w, 4) for w in windows],
        "output_file": "datasets/base_diversity_baseline.jsonl",
    }
    out = DATA_DIR / "base_diversity_baseline.jsonl"
    with open(out, "w", encoding="utf-8") as fh:
        for i, (p, o) in enumerate(zip(prompts, outputs)):
            fh.write(dumps_canonical({
                "gen_id": f"base_{i:04d}",
                "prompt_vi": p,
                "output_vi": o,
            }) + "\n")
    (DATA_DIR / "base_diversity_baseline.json").write_text(
        json.dumps(report, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    print(f"  distinct-2 (200-sample): {report['distinct2_200_sample']}")
    print(f"  per-100 windows: {report['distinct2_per_100_windows']}")
    print(f"  wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
